version: '3.8'
services:
  db_bank:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: bankService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - bankservice-db:/var/lib/postgres/data/
    ports:
      - "54321:5432"

    networks:
      - banknetwork

  bankservice:
    build: .
    image: bankservice:0.0.0.1
    container_name: bankservice
    hostname: bankservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_bank:5432/bankService
    ports:
      - "8081:8080"
    depends_on:
      - db_bank

    networks:
      - banknetwork

volumes:
  bankservice-db:

networks:
  banknetwork:
    external: true